### DEFAULT PROFILE ###
server:
  port: ${PORT:8080}

spring:
  application:
    name: project-case-pix
    version: 1.0.0
  jackson:
    time-zone: Brazil/East
    locale: pt_BR
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

management:
  endpoints:
    web:
      exposure:
        include: health, heapdump

limit:
  max:
    key:
      value:
        legal-person: 20
        natural-person: 5

account:
  key:
    accepted:
      current: corrente
      savings: poupança

